function res = ita_preferences_playrecmidi()

% <ITA-Toolbox>
% This file is part of the ITA-Toolbox. Some rights reserved.
% You can find the license for this m-file in the license.txt file in the ITA-Toolbox folder.
% </ITA-Toolbox>

if nargout == 0 % Show GUI
    ita_preferences_gui_tabs(eval(mfilename), {mfilename}, true);
else
    res = {'samplingRate',44100,'popup_double','Sampling Rate','Specify standard sampling rate for simulation and measurement.[44100|48000|88200|96000|176400|192000]',2;...
        'fftDegree',16,'int','FFT Degree','The fftDegree you like the most. some functions will automatically use this as default',2;...
        'recDeviceID',-1,'int_portAudio','Recording Device','PortAudio Recording Device',2;...
        'playDeviceID', -1,'int_portAudio','Playing Device','PortAudio Play Device, should be the same card as Recording Device',2;...
        'playrecBufferSize', 0,'popup_double','Playrec Buffer Size', 'Input/Output Buffer Size (to reduce glitches choose higher value, 0 means automatic mode).[0|256|512|1024|2048]',2; ...
        'portAudioMonitor' , -1  ,'popup_double','Port Audio Monitor' , '-1: automatic on/off, 0:off, 1:always on [-1|0|1]',2;...
        'out_midi_DeviceID', -1,'int_portMidi','Midi Output Device','Midi Output Device',2;...
        'disable_midi',ismac,'bool','Disable MIDI', 'Check if you have trouble with MIDI (crashes) and dont need it',2;...
        'playrec', 1 ,'playrecFunctionHandle','playrec', 'Use different compilations of playrec. e.g. with ASIO.',3; ...
        };
end