function h = ita_device_list_handle ()

% <ITA-Toolbox>
% This file is part of the application Measurement for the ITA-Toolbox. All rights reserved.
% You can find the license for this m-file in the application folder.
% </ITA-Toolbox>

%% PLEASE DO NOT EDIT THIS FILE !!! - ONLY INTENDED FOR DEVELOPERS


if exist('ita_device_list_ITA.m','file')
    h = @ita_device_list_ITA;
else
    h = @ita_device_list;
end

end