%% Generates examplary DAFF files of various content type and shape

% 5x5 degree grid resolution
alpha_res = 5; 
beta_res = 5;

channels = 1;
default_orient = [ 0 0 0 ]; % yaw pitch roll @ +Y+X-Z (OpenGL)

metadata = [];
metadata = daffv17_add_metadata( metadata, 'Description', 'String', 'Generated OpenDAFF example directivity' );
metadata = daffv17_add_metadata( metadata, 'Creation date', 'String', date );
metadata = daffv17_add_metadata( metadata, 'License', 'String', 'CC BY' );
metadata = daffv17_add_metadata( metadata, 'Generation script', 'String', 'Opendaff-v1.7/matlab/generate_examples.m' );

addpath( 'datafuncs' )

%%
unity_dft_config.channels = 1;
unity_dft_config.freqs = [20 25 31.5 40 50 63 80 100 125 160 ...
                 200 250 315 400 500 630 800 1000 1250 1600 ...
                 2000 2500 3150 4000 5000 6300 8000 10000 12500 16000 20000];
daffv17_write('filename', 'ExampleUnityOmni_ThirdOctave.v17.ms.daff', ...
           'content', 'ms', ...
           'datafunc', @dfUnityMS, ...
           'userdata', unity_dft_config, ...
           'channels', channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', default_orient, ...
           'metadata', metadata);
disp( ' ' )

%%
daffv17_write('filename', 'ExampleUnityUpperHemisphere.v17.ms.daff', ...
           'content', 'ms', ...
           'datafunc', @dfUnityMS, ...
           'channels', channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', default_orient, ...
           'metadata', metadata, ...
           'betarange', [ 90 180 ]);
disp( ' ' )

%%
daffv17_write('filename', 'ExampleUnityLowerHemisphere.v17.ms.daff', ...
           'content', 'ms', ...
           'datafunc', @dfUnityMS, ...
           'channels', channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', default_orient, ...
           'metadata', metadata, ...
           'betarange', [ 0 90 ]);
disp( ' ' )

%%
daffv17_write('filename', 'ExampleUnityFrontalHemisphere.v17.ms.daff', ...
           'content', 'ms', ...
           'datafunc', @dfUnityMS, ...
           'channels', channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', [ 90 0 0 ], ...
           'metadata', metadata, ...
           'alpharange', [ 0 180 ] );
disp( ' ' )

%%
daffv17_write('filename', 'ExampleUnityRearHemisphere.v17.ms.daff', ...
           'content', 'ms', ...
           'datafunc', @dfUnityMS, ...
           'channels', channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', [ -90 0 0 ], ...
           'metadata', metadata, ...
           'alpharange', [ 0 180 ] );
disp( ' ' )

%%
dirac_ir_config.numsamples = 4;
dirac_ir_config.channels = channels;
dirac_ir_config.samplerate = 48000;
daffv17_write('filename', 'ExampleShortDiracOmni_48kHz.v17.ir.daff', ...
           'content', 'ir', ...
           'datafunc', @dfDiracIR, ...
           'userdata', dirac_ir_config, ...
           'channels', channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', default_orient, ...
           'metadata', metadata, ...
           'quantization', 'float32' );
disp( ' ' )

%%
dirac_ir_config.numsamples = 128;
dirac_ir_config.channels = 2;
dirac_ir_config.samplerate = 44100;
daffv17_write('filename', 'ExampleMultiChannelDiracOmni_128_44kHz.v17.ir.daff', ...
           'content', 'ir', ...
           'datafunc', @dfDiracIR, ...
           'userdata', dirac_ir_config, ...
           'channels', dirac_ir_config.channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', default_orient, ...
           'metadata', metadata, ...
           'quantization', 'float32' );
disp( ' ' )

%%
daffv17_write('filename', 'ExampleFigureOfEightFront.v17.ms.daff', ...
           'content', 'ms', ...
           'datafunc', @dfFigureOfEightMS, ...
           'channels', channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', default_orient, ...
           'metadata', metadata, ...
           'quantization', 'float32' );
disp( ' ' )

%%
daffv17_write('filename', 'ExampleFigureOfEightFront.v17.mps.daff', ...
           'content', 'mps', ...
           'datafunc', @dfFigureOfEightMPS, ...
           'channels', channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', default_orient, ...
           'metadata', metadata, ...
           'quantization', 'float32' );
disp( ' ' )

%%
daffv17_write('filename', 'ExampleFigureOfEightSide.v17.ms.daff', ...
           'content', 'ms', ...
           'datafunc', @dfFigureOfEightMS, ...
           'channels', channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', [ 90 0 0 ], ...
           'metadata', metadata, ...
           'quantization', 'float32' );
disp( ' ' )

%%
daffv17_write('filename', 'ExampleLowPass3dBOmni.v17.ms.daff', ...
           'content', 'ms', ...
           'datafunc', @dfLowPass3dBMS, ...
           'channels', channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', default_orient, ...
           'metadata', metadata);
disp( ' ' )

%%
daffv17_write('filename', 'ExampleLowPass6dBOmni.v17.ms.daff', ...
           'content', 'ms', ...
           'datafunc', @dfLowPass6dBMS, ...
           'channels', channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', default_orient, ...
           'metadata', metadata);
disp( ' ' )

%%
daffv17_write('filename', 'ExampleUnityOmni.v17.dft.daff', ...
           'content', 'dft', ...
           'datafunc', @dfUnityDFT, ...
           'channels', channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', default_orient, ...
           'metadata', metadata);
disp( ' ' )

%%
unity_dft_config.channels = 1;
unity_dft_config.length = 128+1;
unity_dft_config.is_symmetric = false;
unity_dft_config.samplerate = 44100;
unity_dft_config.complex_value = 1;
daffv17_write('filename', 'ExampleUnityOmni_128_44kHz.v17.dft.daff', ...
           'content', 'dft', ...
           'datafunc', @dfUnityDFT, ...
           'userdata', unity_dft_config, ...
           'channels', channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', default_orient, ...
           'metadata', metadata);
disp( ' ' )

%%
unity_dft_config.channels = 1;
unity_dft_config.length = 128+1;
unity_dft_config.is_symmetric = false;
unity_dft_config.samplerate = 44100;
unity_dft_config.complex_value = sqrt( 2 ) * ( 1 + 1j );
daffv17_write('filename', 'ExampleUnityOmni_128_44kHz_45deg.v17.dft.daff', ...
           'content', 'dft', ...
           'datafunc', @dfUnityDFT, ...
           'userdata', unity_dft_config, ...
           'channels', channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', default_orient, ...
           'metadata', metadata);
disp( ' ' )

%%
unity_dft_config.channels = 1;
unity_dft_config.length = 128+1;
unity_dft_config.is_symmetric = false;
unity_dft_config.samplerate = 44100;
unity_dft_config.complex_value = -1 + 1i * 0;
daffv17_write('filename', 'ExampleUnityOmni_128_44kHz_phase_inverted.v17.dft.daff', ...
           'content', 'dft', ...
           'datafunc', @dfUnityDFT, ...
           'userdata', unity_dft_config, ...
           'channels', channels, ...
           'alphares', alpha_res, ...
           'betares', beta_res, ...
           'orient', default_orient, ...
           'metadata', metadata);
disp( ' ' )
