Description of strtok
strtok
PURPOSE
Modified version of STRTOK to also return the quotient
SYNOPSIS
function [token, remainder, quotient] = strtok(string, delimiters)
DESCRIPTION
Modified version of STRTOK to also return the quotient
  string = [quotient token remainder]
STRTOK Find token in string.
   STRTOK(S) returns the first token in the string S delimited
   by "white space".   Any leading white space characters are ignored.
   STRTOK(S,D) returns the first token delimited by one of the
   characters in D.  Any leading delimiter characters are ignored.
   [T,R] = STRTOK(...) also returns the remainder of the original
   string.
   If the token is not found in S then R is an empty string and T
   is same as S.
   Copyright 1984-2002 The MathWorks, Inc.
   $Revision: 1.1 $  $Date: 2008-09-03 08:36:22 $
CROSS-REFERENCE INFORMATION
This function calls:
finish TEMPLATE/FINISH Apply given strategy to unknown fields in a string
This function is called by:
m2html M2HTML - Documentation System for Matlab M-files in HTML
mfileparse Parsing of an M-file to obtain synopsis, help and references
searchindex Compute keywords statistics of an M-file
SOURCE CODE
function [token, remainder, quotient] = strtok(string, delimiters)
%Modified version of STRTOK to also return the quotient
%  string = [quotient token remainder]
%STRTOK Find token in string.
%   STRTOK(S) returns the first token in the string S delimited
%   by "white space".   Any leading white space characters are ignored.
%
%   STRTOK(S,D) returns the first token delimited by one of the
%   characters in D.  Any leading delimiter characters are ignored.
%
%   [T,R] = STRTOK(...) also returns the remainder of the original
%   string.
%   If the token is not found in S then R is an empty string and T
%   is same as S.
%
%   Copyright 1984-2002 The MathWorks, Inc.
%   $Revision: 1.1 $  $Date: 2008-09-03 08:36:22 $
token = []; remainder = []; quotient = string;
len = length(string);
if len == 0
    return
end
if (nargin == 1)
    delimiters = [9:13 32]; % White space characters
end
i = 1;
while (any(string(i) == delimiters))
    i = i + 1;
    if (i > len), return, end
end
start = i;
while (~any(string(i) == delimiters))
    i = i + 1;
    if (i > len), break, end
end
finish = i - 1;
token = string(start:finish);
if (nargout >= 2)
    remainder = string(finish + 1:length(string));
end
if (nargout == 3 & start > 1)
    quotient = string(1:start-1);
else
    quotient = [];
end