function [] = daffv17_convert_from_aktools( target_file_path, export_properties, additional_metadata )

export_properties.samplerate = 44100;
export_properties.numsamples = 256;
export_properties.numchannels = 2 * ceil( ( export_properties.hatorange( 2 ) - export_properties.hatorange( 1 ) ) / export_properties.hatores + 1 );

combined_metadata = daffv17_add_metadata( additional_metadata, 'Converter script', 'String', 'daffv17_convert_from_aktools.m' );
combined_metadata = daffv17_add_metadata( combined_metadata, 'Conversion date', 'String', date );

daffv17_write( 'filename', target_file_path, ...
                'datafunc', @dfAKtools, ...
                'userdata', export_properties, ...
                'metadata', combined_metadata, ...
                'content', 'ir', ...
                'alphares', export_properties.alphares, ...
                'alpharange', export_properties.alpharange, ...
                'betares', export_properties.betares, ...
                'betarange', export_properties.betarange, ...
                'orient', [ 0 0 0 ], ...
                'channels', export_properties.numchannels, ...
                'quantization', 'float32' );

