function res = ita_preferences_measurement()
% ITA_PREFERENCES_MEASUREMENT - choose measurement options

% <ITA-Toolbox>
% This file is part of the application Measurement for the ITA-Toolbox. All rights reserved. 
% You can find the license for this m-file in the application folder. 
% </ITA-Toolbox>


%% PLEASE DO NOT EDIT THIS FILE !!! - ONLY INTENDED FOR DEVELOPERS

if nargout == 0 % Show GUI
    ita_preferences_gui_tabs(eval(mfilename), {mfilename}, true);
else
    res = {'MeasuringStation','none','popup_char','MeasuringStation',['Choose your equipment settings[' itaMeasuringStation.getString ']'],2;...
        'useMeasurementChain',false,'bool','Measurement Chain','ccx required! Measurement Chains are used for absolutely calibrated measurements also for transfer functions',2;...
        'calibrationDomain', 'Time' ,'char','Calibration Domain', 'Time or Frequency, specifies whether calibration values are calculated in time or frequency domain.',3;...
        'calibrationFrequencies'       , [2, 250, 1000]  ,'double','Accepted calibration frequencies' , 'List of frequencies, default is 2Hz, 250Hz, 1000Hz',3;...
        'calibrationFrequencyTolerance', 50 ,'double','Calib. Freq. Tolerance in Cent', 'Default is 50 Cent.'                              ,3; ...
        };
end